# Generated by Django 6.0.3 on 2026-03-30 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(verbose_name='Idade')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura (cm)')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentário'), ('light', 'Levemente ativo'), ('moderate', 'Moderadamente ativo'), ('intense', 'Muito ativo'), ('athlete', 'Atleta')], max_length=20, verbose_name='Nível de Atividade')),
                ('goal', models.CharField(choices=[('lose', 'Emagrecimento'), ('maintain', 'Manutenção'), ('gain', 'Hipertrofia / Ganho de Massa')], max_length=20, verbose_name='Objetivo')),
                ('meals_per_day', models.PositiveIntegerField(default=3, verbose_name='Refeições por dia')),
                ('food_restrictions', models.TextField(blank=True, help_text='Ex: vegetariano, sem glúten, sem lactose', verbose_name='Restrições Alimentares')),
                ('food_preferences', models.TextField(blank=True, help_text='Alimentos que o usuário prefere consumir', verbose_name='Preferências Alimentares')),
                ('allergies', models.TextField(blank=True, help_text='Ex: amendoim, frutos do mar', verbose_name='Alergias Alimentares')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Respondido em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
                'ordering': ['-answered_at'],
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_response', models.JSONField(help_text='JSON completo retornado pela IA conforme estrutura do PROMPTS.md', verbose_name='Resposta da IA (JSON)')),
                ('total_calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de Calorias')),
                ('goal_description', models.CharField(blank=True, help_text='Campo "objetivo" retornado pela IA', max_length=100, verbose_name='Objetivo (descritivo)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('anamnese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_plans', to='nutrition.anamnese', verbose_name='Anamnese de origem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Plano Alimentar',
                'verbose_name_plural': 'Planos Alimentares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(help_text='Ex: Café da manhã, Almoço, Jantar', max_length=100, verbose_name='Nome da Refeição')),
                ('description', models.TextField(help_text='Alimentos e quantidades da refeição', verbose_name='Descrição')),
                ('calories', models.PositiveIntegerField(verbose_name='Calorias Estimadas')),
                ('order', models.PositiveIntegerField(default=0, help_text='Posição da refeição dentro do plano (0 = primeira)', verbose_name='Ordem de exibição')),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.dietplan', verbose_name='Plano Alimentar')),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'Refeições',
                'ordering': ['diet_plan', 'order'],
            },
        ),
    ]
