# Generated by Django 6.0.3 on 2026-04-27 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0002_dietjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealRegenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Motivo informado"),
                ),
                (
                    "previous_description",
                    models.TextField(verbose_name="Descrição anterior"),
                ),
                (
                    "previous_calories",
                    models.PositiveIntegerField(verbose_name="Calorias anteriores"),
                ),
                (
                    "previous_raw_meal",
                    models.JSONField(verbose_name="Refeição anterior (JSON)"),
                ),
                (
                    "is_undone",
                    models.BooleanField(default=False, verbose_name="Desfeito"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Gerado em"),
                ),
                (
                    "diet_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regeneration_logs",
                        to="nutrition.dietplan",
                        verbose_name="Plano Alimentar",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regeneration_logs",
                        to="nutrition.meal",
                        verbose_name="Refeição",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_regeneration_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Regeneração",
                "verbose_name_plural": "Logs de Regeneração",
                "ordering": ["-created_at"],
            },
        ),
    ]
